FROM confluentinc/cp-kafka-connect:7.6.0

# Устанавливаем JDBC Sink Connector через Confluent Hub
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest

# Указываем путь к плагинам
ENV CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components