version: '3.8'

networks:
  kafka-net-1:
    driver: bridge
    name: kafka-cluster-network-1
  kafka-net-2:
    driver: bridge
    name: kafka-cluster-network-2

x-schema-registry-common-env: &schema-registry-common-env
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
  SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
  SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: >
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer="prod-secret"
    user_consumer="cons-secret"
    user_kafkaconnect="kafkaconnect-secret";
  SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
  SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: qwerty

x-kafka-common-env: &kafka-common-env
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  # SSL (внутренняя связь)
  KAFKA_SSL_KEYSTORE_TYPE: JKS
  KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.jks
  KAFKA_SSL_KEYSTORE_PASSWORD: qwerty
  KAFKA_SSL_KEY_PASSWORD: qwerty
  KAFKA_SSL_TRUSTSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
  KAFKA_SSL_TRUSTSTORE_PASSWORD: qwerty
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
  # SASL (внешние клиенты)
  KAFKA_ZOOKEEPER_SASL_CLIENT: 'true'
  KAFKA_ZOOKEEPER_SET_ACL: 'true'
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_SUPER_USERS: User:admin
  KAFKA_SASL_JAAS_CONFIG: >
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer="prod-secret"
    user_consumer="cons-secret"
    user_kafkaconnect="kafkaconnect-secret";
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"

services:

  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    platform: linux/arm64
    networks:
      - kafka-net-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kafka
      POSTGRES_USER: kafka
      POSTGRES_PASSWORD: kafka
    volumes:
      - ./common/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10

############################
# KAFKA CLUSTER 1
# bootstrap servers:
# kafka1:19092,kafka2:19093
############################

  zookeeper1:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper1
    platform: linux/arm64
    networks:
      - kafka-net-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
    ports:
      - "2181:2181"
    volumes:
      - ./common/zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
  kafka1-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1-1
    platform: linux/arm64
    hostname: kafka1
    depends_on:
      - zookeeper1
    networks:
      - kafka-net-1
    ports:
      - "9092:9092"
    environment:
      <<: *kafka-common-env
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092
      # Репликация
      # Минимальное количество реплик для отказоустойчивости в двух брокерах (у меня в каждом кластере настроено именно столько) - максимум 2.
      # Для синхронности нужно установить `min.insync.replicas = 2` на брокерах или `replication-factor = 2` в топиках.
      # Но из-за ограничений ноута, при таких настройках у меня всё время что-то отваливается.
      # Поэтому здесь стоит значение 1.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./common/kafka1:/etc/kafka/secrets
  kafka1-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1-2
    platform: linux/arm64
    hostname: kafka2
    depends_on:
      - zookeeper1
    networks:
      - kafka-net-1
    ports:
      - "9093:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093
    volumes:
      - ./common/kafka2:/etc/kafka/secrets
  schema-registry1:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry1
    platform: linux/arm64
    hostname: schema-registry1
    networks:
      - kafka-net-1
    ports:
      - "8081:8081"
    depends_on:
      - kafka1-1
      - kafka1-2
    environment:
      <<: *schema-registry-common-env
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_SSL://kafka1:19092,SASL_SSL://kafka2:19093
      SCHEMA_REGISTRY_HOST_NAME: schema-registry1
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    volumes:
      - ./common/ca:/etc/kafka/secrets

############################
# KAFKA CLUSTER 2
# bootstrap servers:
# kafka3:19094,kafka4:19095
############################

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper2
    platform: linux/arm64
    networks:
      - kafka-net-2
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
    ports:
      - "2182:2182"
    volumes:
      - ./common/zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
  kafka2-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2-1
    platform: linux/arm64
    hostname: kafka3
    depends_on:
      - zookeeper2
    networks:
      - kafka-net-2
    ports:
      - "9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2182
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094
      # Репликация
      # Минимальное количество реплик для отказоустойчивости в двух брокерах (у меня в каждом кластере настроено именно столько) - максимум 2.
      # Для синхронности нужно установить `min.insync.replicas = 2` на брокерах или `replication-factor = 2` в топиках.
      # Но из-за ограничений ноута, при таких настройках у меня всё время что-то отваливается.
      # Поэтому здесь стоит значение 1.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./common/kafka3:/etc/kafka/secrets
  kafka2-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2-2
    platform: linux/arm64
    hostname: kafka4
    depends_on:
      - zookeeper2
    networks:
      - kafka-net-2
    ports:
      - "9095:9095"
    environment:
      <<: *kafka-common-env
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2182
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19095,EXTERNAL://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka4:19095,EXTERNAL://localhost:9095
    volumes:
      - ./common/kafka4:/etc/kafka/secrets
  schema-registry2:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry2
    platform: linux/arm64
    networks:
      - kafka-net-2
    ports:
      - "8079:8079"
    depends_on:
      - kafka2-1
      - kafka2-2
    environment:
      <<: *schema-registry-common-env
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_SSL://kafka3:19094,SASL_SSL://kafka4:19095
      SCHEMA_REGISTRY_HOST_NAME: schema-registry2
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8079
    volumes:
      - ./common/ca:/etc/kafka/secrets

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    platform: linux/arm64
    networks:
      - kafka-net-1
      - kafka-net-2
    ports:
      - "8080:8080"
    depends_on:
      - kafka1-1
      - kafka1-2
      - kafka2-1
      - kafka2-2
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"

      KAFKA_CLUSTERS_0_NAME: cluster-1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19093
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret"
        user_admin="admin-secret"
        user_producer="prod-secret"
        user_consumer="cons-secret"
        user_kafkaconnect="kafkaconnect-secret";
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "qwerty"
      KAFKA_CLUSTERS_0_READONLY_MODE: "false"

      KAFKA_CLUSTERS_1_NAME: cluster-2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka3:19094,kafka4:19095
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret"
        user_admin="admin-secret"
        user_producer="prod-secret"
        user_consumer="cons-secret"
        user_kafkaconnect="kafkaconnect-secret";
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "qwerty"
      KAFKA_CLUSTERS_1_READONLY_MODE: "false"
    volumes:
      - ./common/ca:/etc/kafka/secrets
