# ---------- build stage ----------
FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml .
COPY common/pom.xml common/pom.xml
COPY shop-api/pom.xml shop-api/pom.xml
COPY client-api/pom.xml client-api/pom.xml

COPY . .

RUN mvn -pl client-api -am clean package -DskipTests

# ---------- runtime ----------
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /build/client-api/target/*.jar app.jar

EXPOSE 9197

ENTRYPOINT ["java","-jar","app.jar"]
