FROM maven:4.0.0-rc-5-amazoncorretto-21-debian AS build
WORKDIR /app

# Copy the parent pom.xml (at the root of the build context)
COPY pom-standalone-mod6.xml ./pom.xml

# Copy the module's pom.xml and source code
COPY shop-api/pom.xml ./shop-api/
COPY shop-api/src ./shop-api/src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-ubi10-minimal
WORKDIR /app
COPY --from=build /app/shop-api/target/*.jar app.jar
EXPOSE 9193
ENTRYPOINT ["java", "-jar", "app.jar"]
