version: '3.8'

networks:
  kafka-net-1:
    driver: bridge
    name: kafka-cluster-network-1

services:
  client-api:
    build:
      context: .
      dockerfile: Dockerfile.client
    platform: linux/arm64
    container_name: client-api
    ports:
      - "9197:9197"
    networks:
      - kafka-net-1
    environment:
      BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093
      SCHEMA_REGISTRY_URL: http://schema-registry1:8081
      SHOP_DB_URL: jdbc:postgresql://postgres:5432/shop_db
      CLIENT_DB_URL: jdbc:postgresql://postgres:5432/client_db
      USE_COMMAND_LINE: false
