#security.protocol=SSL
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.keystore.location=/etc/kafka/secrets/keystore.jks
ssl.keystore.password=qwerty
ssl.key.password=qwerty
ssl.truststore.location=/etc/kafka/secrets/truststore.jks
ssl.truststore.password=qwerty
ssl.endpoint.identification.algorithm=
