clusters=source,target

# ???????-????????
source.bootstrap.servers=kafka1:19092,kafka2:19093
source.security.protocol=SASL_SSL
source.sasl.mechanism=PLAIN
source.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

# ???????-??????????
target.bootstrap.servers=kafka3:19094,kafka4:19095
target.security.protocol=SASL_SSL
target.sasl.mechanism=PLAIN
target.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

# ?????? ??? ??????????????
topics=products,allowed-products,client-requests
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy

# ??????????
replication.factor=2

offset.storage.replication.factor=2
config.storage.replication.factor=2
status.storage.replication.factor=2

emit.checkpoints.enabled=true
sync.topic.acls.enabled=true

# Heartbeat ??? ?????????????
heartbeat.interval.ms=10000
refresh.topics.interval.seconds=60

# ssl
source.ssl.truststore.location=/etc/kafka/secrets/truststore.jks
source.ssl.truststore.password=qwerty

target.ssl.truststore.location=/etc/kafka/secrets/truststore.jks
target.ssl.truststore.password=qwerty

source->target.enabled=true
source->target.topics=.*

