server:
  port: 9197

spring:
  docker:
    compose:
      enabled: false
  datasource:
    shop:
      url: ${SHOP_DB_URL}
      username: shop_user
      password: shop_pass
      driver-class-name: org.postgresql.Driver
    client:
      url: ${CLIENT_DB_URL}
      username: client_user
      password: client_pass
      driver-class-name: org.postgresql.Driver
  jpa:
    shop:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    client:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="prod-secret";
  ssl-truststore-password: qwerty
  # producer
  client-requests-event:
    topic: client-requests
    acks: "all"
    retries: 3
    retry-backoff-ms: 1000
    enable-idempotence: true

client-api:
  use-command-line: ${USE_COMMAND_LINE}
