KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer="prod-secret"
    user_consumer="cons-secret"
    user_kafkaconnect="kafkaconnect-secret"
    user_hdfs="hdfs-secret";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    serviceName="kafka.practicum.yandex"
    username="admin"
    password="admin-secret";
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer="prod-secret"
    user_consumer="cons-secret"
    user_kafkaconnect="kafkaconnect-secret"
    user_hdfs="hdfs-secret";
};

ControllerServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    serviceName="kafka"
    username="controller_user"
    password="bitnami";
};
